### ISSUE TITLE
Confusion with versionedSources

### ISSUE THREAD

**Issue by IngwiePhoenix** [cimi/semver-sync#10]
I just installed this tool and wanted to see how it does. My project uses three JSONs:

- package.json (main)
- bower.json (web stuff)
- composer.json (php stuff)

composer.json does not need a version, it uses git tags. But for bower, I added `"versionedSources": "bower.json"` and got this error...it's kinda confusing:

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ semver-sync -v
[ERROR] Version number is out of sync in bower.json, bower.json.
```

I didn't specify it twice. Why is it listed twice?

**Comment by cimi** [comment]
Thanks for reporting!

`bower.json` is verified by default if present, by specifying it in the `verifiedSources` field it made semver-sync check it twice. I've made it treat the sources as a set, so everything will be checked once.
